package bean;
// Generated 27/10/2023 11:42:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VeccUsuario generated by hbm2java
 */
@Entity
@Table(name="vecc_usuario"
    ,catalog="db_victor_cardoso"
)
public class VeccUsuario  implements java.io.Serializable {


     private int veccIdusuario;
     private String veccNome;
     private String veccApelido;
     private String veccCpf;
     private String veccTelefone;
     private String veccEndereco;
     private String veccSenha;

    public VeccUsuario() {
    }

    public VeccUsuario(int veccIdusuario, String veccNome, String veccApelido, String veccCpf, String veccTelefone, String veccEndereco, String veccSenha) {
       this.veccIdusuario = veccIdusuario;
       this.veccNome = veccNome;
       this.veccApelido = veccApelido;
       this.veccCpf = veccCpf;
       this.veccTelefone = veccTelefone;
       this.veccEndereco = veccEndereco;
       this.veccSenha = veccSenha;
    }
   
     @Id 

    
    @Column(name="vecc_idusuario", unique=true, nullable=false)
    public int getVeccIdusuario() {
        return this.veccIdusuario;
    }
    
    public void setVeccIdusuario(int veccIdusuario) {
        this.veccIdusuario = veccIdusuario;
    }

    
    @Column(name="vecc_nome", nullable=false, length=45)
    public String getVeccNome() {
        return this.veccNome;
    }
    
    public void setVeccNome(String veccNome) {
        this.veccNome = veccNome;
    }

    
    @Column(name="vecc_apelido", nullable=false, length=45)
    public String getVeccApelido() {
        return this.veccApelido;
    }
    
    public void setVeccApelido(String veccApelido) {
        this.veccApelido = veccApelido;
    }

    
    @Column(name="vecc_cpf", nullable=false, length=45)
    public String getVeccCpf() {
        return this.veccCpf;
    }
    
    public void setVeccCpf(String veccCpf) {
        this.veccCpf = veccCpf;
    }

    
    @Column(name="vecc_telefone", nullable=false, length=45)
    public String getVeccTelefone() {
        return this.veccTelefone;
    }
    
    public void setVeccTelefone(String veccTelefone) {
        this.veccTelefone = veccTelefone;
    }

    
    @Column(name="vecc_endereco", nullable=false, length=45)
    public String getVeccEndereco() {
        return this.veccEndereco;
    }
    
    public void setVeccEndereco(String veccEndereco) {
        this.veccEndereco = veccEndereco;
    }

    
    @Column(name="vecc_senha", nullable=false, length=45)
    public String getVeccSenha() {
        return this.veccSenha;
    }
    
    public void setVeccSenha(String veccSenha) {
        this.veccSenha = veccSenha;
    }




}


