package bean;
// Generated 27/10/2023 11:42:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VeccVendedor generated by hbm2java
 */
@Entity
@Table(name="vecc_vendedor"
    ,catalog="db_victor_cardoso"
)
public class VeccVendedor  implements java.io.Serializable {


     private int veccIdvendedor;
     private String veccNome;
     private String veccCpf;
     private String veccEndereco;
     private String veccApelido;
     private String veccTelefone;
     private Set veccProdutos = new HashSet(0);
     private Set veccVendas = new HashSet(0);

    public VeccVendedor() {
    }

	
    public VeccVendedor(int veccIdvendedor) {
        this.veccIdvendedor = veccIdvendedor;
    }
    public VeccVendedor(int veccIdvendedor, String veccNome, String veccCpf, String veccEndereco, String veccApelido, String veccTelefone, Set veccProdutos, Set veccVendas) {
       this.veccIdvendedor = veccIdvendedor;
       this.veccNome = veccNome;
       this.veccCpf = veccCpf;
       this.veccEndereco = veccEndereco;
       this.veccApelido = veccApelido;
       this.veccTelefone = veccTelefone;
       this.veccProdutos = veccProdutos;
       this.veccVendas = veccVendas;
    }
   
     @Id 

    
    @Column(name="vecc_idvendedor", unique=true, nullable=false)
    public int getVeccIdvendedor() {
        return this.veccIdvendedor;
    }
    
    public void setVeccIdvendedor(int veccIdvendedor) {
        this.veccIdvendedor = veccIdvendedor;
    }

    
    @Column(name="vecc_nome", length=45)
    public String getVeccNome() {
        return this.veccNome;
    }
    
    public void setVeccNome(String veccNome) {
        this.veccNome = veccNome;
    }

    
    @Column(name="vecc_cpf", length=45)
    public String getVeccCpf() {
        return this.veccCpf;
    }
    
    public void setVeccCpf(String veccCpf) {
        this.veccCpf = veccCpf;
    }

    
    @Column(name="vecc_endereco", length=45)
    public String getVeccEndereco() {
        return this.veccEndereco;
    }
    
    public void setVeccEndereco(String veccEndereco) {
        this.veccEndereco = veccEndereco;
    }

    
    @Column(name="vecc_apelido", length=45)
    public String getVeccApelido() {
        return this.veccApelido;
    }
    
    public void setVeccApelido(String veccApelido) {
        this.veccApelido = veccApelido;
    }

    
    @Column(name="vecc_telefone", length=45)
    public String getVeccTelefone() {
        return this.veccTelefone;
    }
    
    public void setVeccTelefone(String veccTelefone) {
        this.veccTelefone = veccTelefone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="veccVendedor")
    public Set getVeccProdutos() {
        return this.veccProdutos;
    }
    
    public void setVeccProdutos(Set veccProdutos) {
        this.veccProdutos = veccProdutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="veccVendedor")
    public Set getVeccVendas() {
        return this.veccVendas;
    }
    
    public void setVeccVendas(Set veccVendas) {
        this.veccVendas = veccVendas;
    }




}


